### ISSUE TITLE
Update documentation on how to install

### ISSUE THREAD

**Issue by kushthedude** [layer5io/scoop-bucket#3]
Update documentation on how to install in ReadME.md for the Scoop installation of mesheryctl.

**Comment by leecalcote** [comment]
Nice work here on ensuring all instructions are updated. 

Also, need to include how to **update** mesheryctl using Scoop.

Cross-reference issue: https://github.com/meshery/meshery/issues/811

**Comment by kushthedude** [comment]
Fixed in #4
